name: esjzone
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  styled_widget: 0.4.1
  connectivity_plus: 4.0.2
  cookie_jar: 4.0.8
  dio: 5.3.2
  dio_cookie_manager: 3.1.0+1
  html: 0.15.4
  path_provider: ^2.1.0
  flutter_spinkit: 5.2.0
  flex_color_scheme: 7.2.0
  string_validator: 1.0.0
  easy_refresh: ^3.3.2+1
  cached_network_image: ^3.2.3
  flutter: 
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get_storage: ^2.1.1
  flutter_widget_from_html: ^0.10.4
  flutter_rating_bar: ^4.0.1
  url_launcher: ^6.1.12
  flutter_easyloading: ^3.0.5
  package_info_plus: ^4.1.0

dev_dependencies: 
  flutter_lints: 2.0.2
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
  uses-material-design: true

